Repository pace-neutrons/Horace, pull requests merged in 2021-11, with the labels that each got.

#757 Remove unnecessary build code for docs
  cmake/PACE_Docs.cmake
Labels: do-not-test

#759 Fix issues with examples
  documentation/example_codes/ExampleRealJobExecutor.m
  documentation/example_codes/exampleParallelCall.m
Labels: documentation, DO_NOT_CI

#756 small clarifications and additions to the document on how to …
  documentation/smg/07_windows_anvil_node.md
Labels: DO_NOT_CI
