Repository pace-neutrons/Horace, pull requests merged in 2021-03, with the labels that each got.

#604 Set default values to avoid error
  tools/build_config/Jenkinsfile
Labels: CI, bug

#584 Clarify which pipelines vars affect
  tools/build_config/Jenkinsfile
Labels: CI, DO_NOT_CI

#613 Update clone_herbert_branch.ps1
  tools/pwsh/clone_herbert_branch.ps1
Labels: CI, bug

#589 Update 08_setting_up_jenkins_ci.md
  documentation/smg/08_setting_up_jenkins_ci.md
Labels: DO_NOT_CI, documentation

#619 fix sqw refs to allow sqw loader to work
  _test/common_functions/is_cut_equal.m
  _test/test_algorithms/test_cut.m
  _test/test_ascii_column_data/test_read_ascii_data.m
  _test/test_change_crystal/test_change_crystal_1.m
  _test/test_change_crystal/test_change_crystal_2.m
  _test/test_gen_sqw_for_powders/test_combine_cyl.m
  _test/test_gen_sqw_for_powders/test_combine_pow.m
  _test/test_gen_sqw_for_powders/test_gen_sqw_cylinder.m
  _test/test_gen_sqw_workflow/gen_sqw_accumulate_sqw_tests_common.m
  _test/test_gen_sqw_workflow/test_gen_sqw_accumulate_sqw_mex.m
  _test/test_mex_nomex/test_fake_sqw_bin_pix.m
  _test/test_sqw/test_gen_runfiles.m
  _test/test_sqw/test_mushroom_sqw.m
  _test/test_sqw/test_sqw_NaN.m
  _test/test_sqw/test_sqw_main.m
  _test/test_sqw_file/create_testdata.m
  _test/test_sqw_file/test_faccess_sqw_v2.m
  _test/test_sqw_file/test_faccess_sqw_v3.m
  _test/test_sqw_file/test_faccess_sqw_v3_3.m
  _test/test_sqw_file/test_file_input.m
  _test/test_sqw_file/test_read_all.m
  _test/test_sqw_file/test_sqw_file_read_write.m
  _test/test_sqw_file/test_write_then_read.m
  _test/test_sym_op/test_cut_sqw_sym.m
  _test/test_symmetrisation/test_symm.m
  _test/test_tobyfit/test_refine_crystal/test_tobyfit_refine_crystal_1.m
  horace_core/@d2d_old/change_crystal.m
  horace_core/algorithms/gen_sqw_cylinder.m
  horace_core/algorithms/gen_sqw_powder.m
  horace_core/algorithms/write_nsqw_to_sqw.m
  horace_core/horace_function_utils/horace_function_call_method.m
  horace_core/horace_function_utils/horace_function_parse_input.m
  horace_core/horace_function_utils/private/is_horace_data_object.m
  horace_core/sqw/@SQWDnDBase/func_eval.m
  horace_core/sqw/@rundatah/private/calc_sqw_.m
  horace_core/sqw/@sqw/head.m
  horace_core/sqw/@sqw/is_sqw_type_file.m
  horace_core/sqw/@sqw/private/cut_sqw_main_single.m
  horace_core/sqw/@sqw/private/cut_sqw_sym_main.m
  horace_core/sqw/@sqw/private/cut_sqw_sym_main_single.m
  horace_core/sqw/@sqw/private/make_sqw_from_data.m
  horace_core/sqw/@sqw/section.m
  horace_core/sqw/@sqw/spe.m
  horace_core/sqw/@sqw/sqw.m
  horace_core/sqw/file_io/@dnd_binfile_common/build_app_header.m
  horace_core/sqw/file_io/@dnd_binfile_common/dnd_binfile_common.m
  horace_core/sqw/file_io/@dnd_binfile_common/private/common_init_logic_.m
  horace_core/sqw/file_io/@faccess_sqw_v2/private/upgrade_file_format_.m
  horace_core/sqw/file_io/@faccess_sqw_v3/private/put_instr_sampl_info_.m
  horace_core/sqw/file_io/@faccess_sqw_v3/private/upgrade_file_format_.m
  horace_core/sqw/file_io/@sqw_binfile_common/get_sqw.m
  horace_core/sqw/file_io/@sqw_binfile_common/private/extract_correct_subobj_.m
  horace_core/sqw/file_io/@sqw_binfile_common/put_sqw.m
  horace_core/sqw/file_io/@sqw_binfile_common/sqw_binfile_common.m
  horace_core/sqw/file_io/sqw_formats_factory.m
Labels: Herbert_sqw_rewrite_feature

#621 Disable unstable tests
  _test/disabled_tests.md
  _test/test_gen_sqw_workflow/test_gen_sqw_accumulate_sqw_herbert.m
  _test/test_gen_sqw_workflow/test_gen_sqw_accumulate_sqw_parpool.m
Labels: Parallel

#588 Fix failing docs due to paths and permissions
  cmake/PACE_Docs.cmake
  tools/build_config/Jenkinsfile
  tools/build_config/build.ps1
  tools/build_config/build.sh
Labels: CI, do-not-build

#620 DnD API transfer
  _test/test_dnd_class/test_eval.m
  _test/test_dnd_class/test_has_pixels.m
  _test/test_dnd_class/test_migrated_apis.m
  _test/test_dnd_class/test_migrated_apis_data.mat
  _test/test_dnd_class/test_smooth.m
  _test/test_sqw_class/test_eval.m
  _test/test_sqw_class/test_migrated_apis.m
  _test/test_sqw_class/test_migrated_apis_data.mat
  _test/test_sqw_class/test_smooth.m
  _test/test_sqw_class/test_test_sqw_utils.m
  documentation/diagrams/sqw-dnd.drawio
  horace_core/admin/modify_pix_ranges.m
  horace_core/sqw/@DnDBase/DnDBase.m
  horace_core/sqw/@DnDBase/dimensions.m
  horace_core/sqw/@DnDBase/has_pixels.m
  horace_core/sqw/@DnDBase/sqw_eval_pix_.m
  horace_core/sqw/@SQWDnDBase/SQWDnDBase.m
  horace_core/sqw/@SQWDnDBase/calculate_q_bins.m
  horace_core/sqw/@SQWDnDBase/calculate_qw_bins.m
  horace_core/sqw/@SQWDnDBase/compact.m
  horace_core/sqw/@SQWDnDBase/dimensions.m
  horace_core/sqw/@SQWDnDBase/disp2sqw_eval.m
  horace_core/sqw/@SQWDnDBase/dispersion.m
  horace_core/sqw/@SQWDnDBase/func_eval.m
  horace_core/sqw/@SQWDnDBase/get_proj_and_pbin.m
  horace_core/sqw/@SQWDnDBase/private/smooth_dnd.m
  horace_core/sqw/@SQWDnDBase/private/smooth_func_gaussian.m
  horace_core/sqw/@SQWDnDBase/private/smooth_func_hat.m
  horace_core/sqw/@SQWDnDBase/private/smooth_func_resolution.m
  horace_core/sqw/@SQWDnDBase/sigvar_get.m
  horace_core/sqw/@SQWDnDBase/smooth.m
  horace_core/sqw/@SQWDnDBase/smooth_units.m
  horace_core/sqw/@SQWDnDBase/sqw_eval.m
  horace_core/sqw/@SQWDnDBase/sqw_eval_nopix_.m
  horace_core/sqw/@SQWDnDBase/xye.m
  horace_core/sqw/@d1d/symmetrise_horace_1d.m
  horace_core/sqw/@sqw/copy.m
  horace_core/sqw/@sqw/func_eval.m
  horace_core/sqw/@sqw/get_proj_and_pbin.m
  horace_core/sqw/@sqw/sqw.m
  horace_core/sqw/@sqw/sqw_eval_pix_.m
Labels: Herbert_sqw_rewrite_feature

#632 Update build.ps1
  cmake/PACE_Docs.cmake
  tools/build_config/Jenkinsfile
  tools/build_config/build.ps1
  tools/build_config/build.sh
Labels: CI, bug

#635 Fix erroneous print
  _test/test_sqw/test_PixelData.m
  _test/test_sqw_file/test_hdf_pix_group.m
  _test/test_sqw_file/test_sqw_formats_factory.m
Labels: bug

#638 509a extended dnd multifit plus 288 updates
  _test/test_symmetrisation/test_symm.m
  horace_core/horace_function_utils/horace_function_call_method.m
  horace_core/horace_function_utils/horace_function_parse_input.m
  horace_core/horace_function_utils/horace_function_squeeze_datasource.m
  horace_core/horace_function_utils/private/is_horace_data_object.m
  horace_core/sqw/@DnDBase/DnDBase.m
  horace_core/sqw/@DnDBase/cut_dnd_main.m
  horace_core/sqw/@DnDBase/data_bin_limits.m
  horace_core/sqw/@DnDBase/mask.m
  horace_core/sqw/@SQWDnDBase/SQWDnDBase.m
  horace_core/sqw/@SQWDnDBase/cut_dnd_calc_ubins.m
  horace_core/sqw/@SQWDnDBase/mask.m
  horace_core/sqw/@SQWDnDBase/mask_points.m
  horace_core/sqw/@d1d/cut.m
  horace_core/sqw/@d1d/d1d.m
  horace_core/sqw/@d2d/calculate_transformation_matrix.m
  horace_core/sqw/@d2d/compare_sym_axes.m
  horace_core/sqw/@d2d/cut.m
  horace_core/sqw/@d2d/d2d.m
  horace_core/sqw/@d2d/get.m
  horace_core/sqw/@d2d/multifit_sqw.m
  horace_core/sqw/@d2d/private/combine_2d.m
  horace_core/sqw/@d2d/private/rebin_2d.m
  horace_core/sqw/@d2d/private/rebin_2d_1axis.m
  horace_core/sqw/@d2d/private/rebin_2d_1axis_finegrid.m
  horace_core/sqw/@d2d/private/rebin_2d_1axis_multibins.m
  horace_core/sqw/@d2d/private/symmetrise_2d.m
  horace_core/sqw/@d2d/private/symmetrise_2d_1axis.m
  horace_core/sqw/@d2d/private/symmetrise_2d_diag.m
  horace_core/sqw/@d2d/symmetrise_horace_2d.m
  horace_core/sqw/@d2d/test_symmetrisation_plane.m
  horace_core/sqw/@d2d/test_symmetrisation_plane_digaonal.m
  horace_core/sqw/@d3d/cut.m
  horace_core/sqw/@d3d/d3d.m
  horace_core/sqw/@d4d/cut.m
  horace_core/sqw/@d4d/d4d.m
  horace_core/sqw/@sqw/recompute_img_range.m
  horace_core/sqw/@sqw/sigvar_get.m
  horace_core/sqw/@sqw/sqw.m
Labels: Herbert_sqw_rewrite_feature

#630 Write SMG for using PixelData
  documentation/smg/17_pixel_data.md
  horace_core/sqw/PixelData/@PixelData/PixelData.m
  horace_core/sqw/PixelData/@PixelData/get_data.m
  horace_core/sqw/PixelData/@PixelData/get_pixels.m
  horace_core/sqw/PixelData/@PixelData/recalc_pix_range.m
Labels: DO_NOT_CI
