Repository pace-neutrons/Horace, pull requests merged in 2023-09, with the labels that each got.

#1210 update urls for documentation in documentation
  documentation/user_docs/README.md
Labels: documentation, DO_NOT_CI

#1217 Re-add deprecated fake_sqw
  horace_core/algorithms/fake_sqw.m
Labels: DO_NOT_CI

#1218 Fix compact for <4d objects
  _test/test_sqw_class/test_compact.m
  horace_core/sqw/@DnDBase/compact.m
Labels: bug

#1224 Sample misalignment docs
  documentation/user_docs/docs/manual/Correcting_for_sample_misalignment.rst
Labels: documentation, DO_NOT_CI

#1196 Fix alignment issues in both fb and mb forms
  _test/test_change_crystal/test_change_crystal_bragg_coarse.m
  _test/test_change_crystal/test_change_crystal_bragg_fine.m
  _test/test_sqw_pixels/test_PixelAlignment.m
  horace_core/sqw/@DnDBase/change_crystal.m
  horace_core/sqw/@sqw/apply_alignment.m
  horace_core/sqw/PixelData/@PixelDataBase/PixelDataBase.m
  horace_core/sqw/PixelData/@PixelDataBase/private/pack_get_pix_result_.m
  horace_core/sqw/PixelData/@PixelDataBase/private/realign_.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/apply.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/apply_alignment.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/get_raw_data.m
  horace_core/sqw/PixelData/@PixelDataMemory/PixelDataMemory.m
  horace_core/sqw/PixelData/@PixelDataMemory/apply.m
  horace_core/sqw/PixelData/@PixelDataMemory/apply_alignment.m
Labels: bug

#1226 Add converter for legacy multifit
  tools/mf_leg_to_new.py
Labels: DO_NOT_CI

#1290 up-to-date description of the Horace installation on IDAAAS …
  documentation/smg/10_build_release_process.md
  documentation/smg/11_ISIS_release.md
Labels: documentation, DO_NOT_CI, do-not-build
