Repository pace-neutrons/Horace, pull requests merged in 2023-07, with the labels that each got.

#1074 Make C and MATLAB serialisers return corresponding errors
  _LowLevelCode/cpp/serialiser/c_deserialize.cpp
  _LowLevelCode/cpp/serialiser/c_serialize.cpp
  _test/test_serializers/test_cpp_deserialize.m
  herbert_core/utilities/misc/hlp_deserialize.m
  herbert_core/utilities/misc/hlp_serialize.m
Labels: bug

#1067 Fix section and add unit tests
  _test/test_sqw_class/test_section.m
  documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst
  horace_core/sqw/@DnDBase/section.m
  horace_core/sqw/@sqw/section.m
Labels: bug, Testing

#1086 Fix missing ldr on return
  horace_core/sqw/@sqw/sqw.m
Labels: bug

#1030 Add sym docs
  documentation/user_docs/docs/manual/Generating_SQW_files.rst
  documentation/user_docs/docs/manual/List_of_functions.rst
  documentation/user_docs/docs/manual/Symmetrising_etc.rst
  documentation/user_docs/docs/manual/symexample.png
Labels: documentation, DO_NOT_CI

#1097 Fix CMake warnings
  CMakeLists.txt
  _LowLevelCode/cpp/test/get_ascii_file.tests/CMakeLists.txt
  cmake/shared/PACE_FindGTest.cmake
Labels: Build

#1101 Remove remaining cut_sqw_sym functions
  horace_core/sqw/@SQWDnDBase/private/cut_parse_inputs_.m
  horace_core/sqw/@sqw/private/cut_sqw_read_data.m
  horace_core/sqw/@sqw/private/cut_sqw_sym_main.m
  horace_core/sqw/@sqw/private/cut_sqw_sym_main_single.m
Labels: Technical Debt

#1099 Deprecate specific refine_crystal_*; remove function utils folder
  horace_core/algorithms/refine_crystal_dnd.m
  horace_core/algorithms/refine_crystal_horace.m
  horace_core/horace_function_utils/AAAREADME.txt
  horace_core/horace_function_utils/horace_function_call_method.m
  horace_core/horace_function_utils/horace_function_pack_output.m
  horace_core/horace_function_utils/horace_function_parse_input.m
  horace_core/horace_function_utils/horace_function_squeeze_datasource.m
  horace_core/horace_function_utils/private/is_filename.m
  horace_core/horace_function_utils/private/is_horace_data_file_opt.m
  horace_core/horace_function_utils/private/is_horace_data_object.m
  horace_core/horace_init.m
  horace_core/refine_crystal_sqw.m
Labels: Technical Debt

#1079 Add test comparing mem & fb diff paged; fix reporting of column name
  _test/test_sqw_class/test_equal_to_tol.m
  horace_core/sqw/PixelData/@PixelDataBase/equal_to_tol.m
Labels: Testing

#1106 updates to sqw description documentation
  documentation/add/07-sqw_redesign.md
  documentation/diagrams/axes_block.png
  documentation/diagrams/dnd.png
  documentation/diagrams/new_projection.png
  documentation/diagrams/sqw-dnd_new.drawio
  documentation/presentations/AlignmentState.pptx
  horace_core/sqw/coord_transform/@aProjectionBase/aProjectionBase.m
Labels: documentation, DO_NOT_CI

#1110 Add file-backed scale factor to hor_config
  horace_core/configuration/@hor_config/hor_config.m
  horace_core/sqw/PixelData/@PixelDataBase/PixelDataBase.m
Labels: enhancement

#1131 Hotfix `test_faccess_sqw_v4` and `test_noisify`
  _test/test_sqw_class/test_noisify.m
  _test/test_sqw_file/test_faccess_sqw_v4.m
Labels: bug

#1077 Some cleaning up of ok-mess in `mfclass`
  _benchmarking/bm_tobyfit_fit/benchmark_tobyfit_fit.m
  herbert_core/applications/multifit/@mfclass/add_bbind.m
  herbert_core/applications/multifit/@mfclass/add_bind.m
  herbert_core/applications/multifit/@mfclass/add_bind_private_.m
  herbert_core/applications/multifit/@mfclass/add_mask_private_.m
  herbert_core/applications/multifit/@mfclass/clear_bbind.m
  herbert_core/applications/multifit/@mfclass/clear_bind.m
  herbert_core/applications/multifit/@mfclass/clear_bind_private_.m
  herbert_core/applications/multifit/@mfclass/clear_bpin.m
  herbert_core/applications/multifit/@mfclass/clear_free_private_.m
  herbert_core/applications/multifit/@mfclass/clear_fun_private_.m
  herbert_core/applications/multifit/@mfclass/clear_mask.m
  herbert_core/applications/multifit/@mfclass/clear_pin.m
  herbert_core/applications/multifit/@mfclass/clear_pin_private_.m
  herbert_core/applications/multifit/@mfclass/mfclass.m
  herbert_core/applications/multifit/@mfclass/private/fun_parse.m
  herbert_core/applications/multifit/@mfclass/private/indices_parse.m
  herbert_core/applications/multifit/@mfclass/private/indicies_parse.m
  herbert_core/applications/multifit/@mfclass/private/is_valid_function_handles.m
  herbert_core/applications/multifit/@mfclass/private/pin_alter.m
  herbert_core/applications/multifit/@mfclass/private/pin_parse.m
  herbert_core/applications/multifit/@mfclass/private/set_fun_private_.m
  herbert_core/applications/multifit/@mfclass/remove_data.m
  herbert_core/applications/multifit/@mfclass/replace_data.m
  herbert_core/applications/multifit/@mfclass/set_bbind.m
  herbert_core/applications/multifit/@mfclass/set_bind.m
  herbert_core/applications/multifit/@mfclass/set_bpin.m
  herbert_core/applications/multifit/@mfclass/set_free_private_.m
  herbert_core/applications/multifit/@mfclass/set_pin.m
  herbert_core/applications/multifit/@mfclass/set_pin_private_.m
Labels: Technical Debt

#1113 Make Symop serializable
  _test/test_serializers/test_serialize_symop.m
  horace_core/symop/@Symop/Symop.m
  horace_core/symop/@SymopGeneral/SymopGeneral.m
  horace_core/symop/@SymopIdentity/SymopIdentity.m
  horace_core/symop/@SymopReflection/SymopReflection.m
  horace_core/symop/@SymopRotation/SymopRotation.m
Labels: enhancement

#1129 Make split fb-safe
  horace_core/sqw/@sqw/split.m
Labels: File-based

#1130 Fileback `calculate_qw_pixels`
  horace_core/sqw/@sqw/calculate_qw_pixels.m
Labels: File-based

#1145 Updated jenkins_ci SMG to work with Notepad++
  documentation/smg/08_setting_up_jenkins_ci.md
Labels: DO_NOT_CI

#1138 Fix date time comparison once and for all
  _test/test_sqw_class/test_equal_to_tol.m
  herbert_core/utilities/maths/equal_to_tol.m
Labels: bug

#1095 1066 Add filebacking to section
  _test/test_sqw_class/test_section.m
  horace_core/sqw/@sqw/section.m
Labels: File-based

#1043 Update compact to new sqw/dnd style
  _test/test_sqw_class/test_compact.m
  herbert_core/utilities/maths/sum_dimensions.m
  horace_core/sqw/@DnDBase/compact.m
  horace_core/sqw/@DnDBase/data_bin_limits.m
  horace_core/sqw/@SQWDnDBase/SQWDnDBase.m
  horace_core/sqw/@SQWDnDBase/compact.m
  horace_core/sqw/@sqw/compact.m
  horace_core/sqw/@sqw/section.m
Labels: bug

#1132 Remove `combine_cuts` make `is_cut_equal` use `combine_sqw`
  _test/common_functions/combine_cuts.m
  _test/common_functions/is_cut_equal.m
  horace_core/sqw/@sqw/combine_cuts.m
  horace_core/sqw/@sqw/combine_sqw.m
  horace_core/sqw/@sqw/is_cut_equal.m
  horace_core/sqw/@sqw/sqw.m
Labels: File-based

#1096 Rename `finalise` to `finish_dump`
  horace_core/sqw/@sqw/coordinates_calc.m
  horace_core/sqw/@sqw/func_eval.m
  horace_core/sqw/@sqw/private/cut_accumulate_data_.m
  horace_core/sqw/@sqw/private/do_sqw_eval_average_filebacked_.m
  horace_core/sqw/@sqw/private/do_sqw_eval_filebacked_.m
  horace_core/sqw/@sqw/section.m
  horace_core/sqw/@sqw/shift_pixels.m
  horace_core/sqw/@sqw/symmetrise_sqw.m
  horace_core/sqw/@sqw/tobyfit_DGdisk_resconv.m
  horace_core/sqw/@sqw/tobyfit_DGfermi_resconv.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/do_unary_op.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/mask.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/noisify.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/private/binary_op_double_.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/private/binary_op_pixels_.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/private/binary_op_scalar_.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/private/binary_op_sigvar_.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/private/set_raw_data_.m
  horace_core/sqw/PixelData/@PixelDataFileBacked/set_raw_fields.m
  horace_core/utilities/sort_pix.m
Labels: enhancement, File-based

#1153 Fix use of outdated `pix.DEFAULT_PAGE_SIZE`
  _test/test_sqw_class/test_eval.m
  horace_core/sqw/@sqw/private/do_sqw_eval_average_filebacked_.m
  horace_core/sqw/@sqw/private/do_sqw_eval_filebacked_.m
Labels: bug
