Repository pace-neutrons/Horace, pull requests merged in 2023-11, with the labels that each got.

#1363 Spaghetti Plot Fixes
  horace_core/spaghetti_plot.m
  horace_core/sqw/coord_transform/@aProjectionBase/aProjectionBase.m
Labels: bug, enhancement

#1368 Remove spinw related files
  horace_core/functions/spinw_disp.m
  horace_core/functions/spinw_gauss_sqw.m
  horace_core/functions/spinw_sho_sqw.m
  horace_core/functions/spinw_sqw.m
  horace_core/utilities/spinw_setpar.m
Labels: Technical Debt

#1228 Add example script documenting dnd sqw differences to docs
  documentation/user_docs/docs/example_scripts/dnd_vs_sqw.rst
  documentation/user_docs/docs/images/dnd_vs_sqw_fig1.jpg
  documentation/user_docs/docs/images/dnd_vs_sqw_fig2.jpg
  documentation/user_docs/docs/images/dnd_vs_sqw_fig3.jpg
  documentation/user_docs/docs/images/dnd_vs_sqw_fig4.jpg
  documentation/user_docs/docs/images/dnd_vs_sqw_fig5.jpg
  documentation/user_docs/docs/images/dnd_vs_sqw_fig6.jpg
Labels: do-not-merge, documentation, do-not-build

#1227 Add example script documenting diagnostic features to docs
  documentation/user_docs/docs/example_scripts/horace_diagnostics.rst
  documentation/user_docs/docs/images/DataDiagnostics_fig1.jpg
  documentation/user_docs/docs/images/DataDiagnostics_fig2.png
  documentation/user_docs/docs/images/DataDiagnostics_fig3.jpg
  documentation/user_docs/docs/images/DataDiagnostics_fig4.jpg
  documentation/user_docs/docs/images/DataDiagnostics_fig5.jpg
  documentation/user_docs/docs/images/DataDiagnostics_fig6.jpg
  documentation/user_docs/docs/images/DataDiagnostics_fig7.jpg
  documentation/user_docs/docs/images/DataDiagnostics_fig8.jpg
  documentation/user_docs/docs/images/DataDiagnostics_fig9.jpg
Labels: do-not-merge, documentation, do-not-build

#1379 Added PowerPoint presentation on PageOp design
  documentation/presentations/PageOp_in_Horace.pptx
Labels: DO_NOT_CI, do-not-build

#1381 Return error estimates from `refine_crystal`
  _test/test_change_crystal/test_refine_crystal.m
  horace_core/lattice_functions/refine_crystal.m
Labels: enhancement

#1406 Add variable width spaghetti plot
  horace_core/spaghetti_plot.m
Labels: enhancement
