Repository pace-neutrons/Horace, pull requests merged in 2023-12, with the labels that each got.

#1418 Modify tests to ensure pixels
  _test/test_sym_op/test_cut_sqw_sym.m
Labels: bug, Testing

#1424 Add fitting file-backed tests for Toby/multifit
  _test/test_TF_components/test_tobyfit_cuts.m
  _test/test_TF_let/test_tobyfit_let_cuts.m
  _test/test_multifit/test_multifit_horace_1.m
Labels: Testing

#1443 Docs fix actually needed empty newline removed
  horace_core/configuration/@hpc_config/hpc_config.m
Labels: DO_NOT_CI
