Repository pace-neutrons/Horace, pull requests merged in 2024-01, with the labels that each got.

#1461 cache.py updated to python 3 and iDAAAS version of Python
  horace_core/admin/cache.py
Labels: do-not-build

#1478 Enable parallel cut tests
  _test/test_algorithms/test_parallel_cut.m
Labels: Testing

#1440 Removing references to redundant usage of combine_equivalent_zones
  documentation/user_docs/docs/manual/FAQ.rst
  documentation/user_docs/docs/manual/Symmetrising_etc.rst
  documentation/user_docs/docs/manual/symmeterize_equivalent_zones_description.bak_Re#1447
Labels: documentation, DO_NOT_CI, do-not-test, do-not-build

#1471 Chunking Tobyfit algorithm
  _test/test_TF_components/test_tobyfit_cuts.m
  _test/test_TF_components/test_tobyfit_cuts_output.mat
  _test/test_TF_components/test_tobyfit_refine_moderator.m
  _test/test_TF_let/test_tobyfit_let_cuts.m
  _test/test_TF_let/test_tobyfit_let_cuts_output.mat
  horace_core/Tobyfit/calculate_q.m
  horace_core/Tobyfit/tobyfit_DGdisk_resconv_init.m
  horace_core/Tobyfit/tobyfit_DGfermi_resconv_init.m
  horace_core/sqw/@sqw/tobyfit_DGdisk_resconv.m
  horace_core/sqw/@sqw/tobyfit_DGfermi_resconv.m
Labels: enhancement, Tobyfit

#1507 Remove duplicated menu item from toctree
  documentation/user_docs/docs/Horace_manual.rst
Labels: documentation, DO_NOT_CI

#1500 Migrate Jenkins CI to Rocky8
  tools/build_config/Jenkinsfile
Labels: CI, DO_NOT_CI

#1462 Add `split` description
  herbert_core/utilities/classes/@object_lookup/rand_ind.m
Labels: documentation, DO_NOT_CI
